# Generated by Django 4.2 on 2023-05-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='guest', max_length=25),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Available in Lict Library', max_length=50),
        ),
    ]
